name: Release

on:
  workflow_dispatch:
    inputs:
      versionLevel:
        description: 'Version level (must be one of major, minor, patch)'
        required: true
      commitMessage:
        description: 'Release/commit message'
        required: true

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Configure Git
      run: |
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git config --local user.name "${GITHUB_ACTOR}"

    - name: Build & Publish
      run: |
        echo Version level: ${{ github.event.inputs.versionLevel }}
        npm ci
        npm run build --if-present
        npm version ${{ github.event.inputs.versionLevel }} --message "${{ github.event.inputs.commitMessage }}"
        git push --follow-tags
        npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
